"""
LLM generator for RAG-based response generation with citations.
Uses Qwen-3 for generating contextualized responses.
"""
import torch
from typing import List, Dict, Optional
from dataclasses import dataclass
from transformers import AutoModelForCausalLM, AutoTokenizer


@dataclass
class GenerationConfig:
    """Configuration for LLM generation."""
    max_new_tokens: int = 512
    temperature: float = 0.7
    top_p: float = 0.9
    top_k: int = 50
    do_sample: bool = True
    repetition_penalty: float = 1.1


@dataclass
class GeneratedResponse:
    """Response generated by the LLM."""
    query: str
    response: str
    citations: List[Dict]
    context_used: str
    model_name: str


class LLMGenerator:
    """
    LLM-based response generator for RAG system.
    Uses Qwen-3 or compatible models for contextualized generation.
    """

    def __init__(self,
                 model_name: str = "Qwen/Qwen2.5-1.5B-Instruct",
                 device: Optional[str] = None,
                 load_in_8bit: bool = False):
        """
        Initialize the LLM generator.

        Args:
            model_name: Name of the HuggingFace model to use
            device: Device to use ('cuda', 'cpu', or None for auto)
            load_in_8bit: Whether to load model in 8-bit precision
        """
        self.model_name = model_name

        # Set device
        if device is None:
            self.device = "cuda" if torch.cuda.is_available() else "cpu"
        else:
            self.device = device

        print(f"Loading LLM: {model_name} on {self.device}...")

        # Load tokenizer
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            trust_remote_code=True
        )

        # Load model
        load_kwargs = {
            "trust_remote_code": True,
            "torch_dtype": torch.float16 if self.device == "cuda" else torch.float32,
        }

        if load_in_8bit and self.device == "cuda":
            load_kwargs["load_in_8bit"] = True
        else:
            load_kwargs["device_map"] = self.device

        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            **load_kwargs
        )

        # Set padding token if not set
        if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token

        self.model.eval()
        print(f"✓ Model loaded successfully")

    def _format_context_with_citations(self,
                                       retrieved_chunks: List[Dict],
                                       include_metadata: bool = True) -> tuple[str, List[Dict]]:
        """
        Format retrieved chunks into context with citation markers.

        Args:
            retrieved_chunks: List of retrieved chunk dictionaries
            include_metadata: Whether to include metadata in context

        Returns:
            Tuple of (formatted_context, citations_list)
        """
        context_parts = []
        citations = []

        for i, chunk in enumerate(retrieved_chunks, 1):
            citation_id = f"[{i}]"

            # Extract chunk information
            text = chunk.get('text', '')
            metadata = chunk.get('metadata', {})
            score = chunk.get('score', 0.0)

            # Format context entry
            if include_metadata:
                section = metadata.get('section_title', 'Unknown Section')
                doc_id = metadata.get('arxiv_id', 'Unknown')
                context_parts.append(
                    f"{citation_id} (Source: {doc_id}, Section: {section}, Relevance: {score:.2f})\n{text}"
                )
            else:
                context_parts.append(f"{citation_id} {text}")

            # Store citation information
            citations.append({
                'citation_id': citation_id,
                'arxiv_id': metadata.get('arxiv_id', 'Unknown'),
                'title': metadata.get('title', 'Unknown'),
                'section_title': metadata.get('section_title', 'Unknown'),
                'score': score,
                'text_preview': text[:200] + "..." if len(text) > 200 else text
            })

        formatted_context = "\n\n".join(context_parts)
        return formatted_context, citations

    def _build_prompt(self, query: str, context: str) -> str:
        """
        Build the prompt for the LLM with retrieved context.

        Args:
            query: User query
            context: Retrieved context with citations

        Returns:
            Formatted prompt string
        """
        system_prompt = """You are a helpful research assistant specialized in answering questions about scientific papers.
Your task is to answer questions based ONLY on the provided context from research papers.

Guidelines:
1. Base your answer strictly on the provided context
2. Cite sources using the citation markers [1], [2], etc. from the context
3. If the context doesn't contain enough information, say so clearly
4. Be concise but comprehensive
5. When citing, place the citation marker [X] at the end of the relevant sentence or claim"""

        user_prompt = f"""Context from research papers:

{context}

Question: {query}

Please provide a detailed answer based on the context above, including citations."""

        # Format for chat models (Qwen format)
        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

        # Apply chat template
        formatted_prompt = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        return formatted_prompt

    def generate_response(self,
                         query: str,
                         retrieved_chunks: List[Dict],
                         config: Optional[GenerationConfig] = None) -> GeneratedResponse:
        """
        Generate a response based on the query and retrieved context.

        Args:
            query: User query
            retrieved_chunks: List of retrieved chunks with metadata
            config: Generation configuration

        Returns:
            Generated response with citations
        """
        if config is None:
            config = GenerationConfig()

        # Format context with citations
        formatted_context, citations = self._format_context_with_citations(retrieved_chunks)

        # Build prompt
        prompt = self._build_prompt(query, formatted_context)

        # Tokenize
        inputs = self.tokenizer(
            prompt,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=4096  # Adjust based on model's max length
        ).to(self.device)

        # Generate
        with torch.no_grad():
            outputs = self.model.generate(
                **inputs,
                max_new_tokens=config.max_new_tokens,
                temperature=config.temperature,
                top_p=config.top_p,
                top_k=config.top_k,
                do_sample=config.do_sample,
                repetition_penalty=config.repetition_penalty,
                pad_token_id=self.tokenizer.pad_token_id,
                eos_token_id=self.tokenizer.eos_token_id,
            )

        # Decode response
        full_output = self.tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Extract just the response (remove the prompt)
        # For chat models, the response comes after the last assistant marker
        response = self._extract_response(full_output, prompt)

        return GeneratedResponse(
            query=query,
            response=response,
            citations=citations,
            context_used=formatted_context,
            model_name=self.model_name
        )

    def _extract_response(self, full_output: str, prompt: str) -> str:
        """
        Extract the generated response from the full output.

        Args:
            full_output: Full generated text
            prompt: Original prompt

        Returns:
            Extracted response
        """
        # Try to find common assistant markers
        markers = ["<|im_start|>assistant", "Assistant:", "assistant\n"]

        for marker in markers:
            if marker in full_output:
                # Split on marker and take the last part
                parts = full_output.split(marker)
                if len(parts) > 1:
                    response = parts[-1].strip()
                    # Remove end marker if present
                    if "<|im_end|>" in response:
                        response = response.split("<|im_end|>")[0].strip()
                    return response

        # Fallback: try to remove the prompt
        if prompt in full_output:
            response = full_output.replace(prompt, "").strip()
            return response

        # Last resort: return full output
        return full_output.strip()

    def format_response_with_sources(self, generated_response: GeneratedResponse) -> str:
        """
        Format the response with source citations for display.

        Args:
            generated_response: Generated response object

        Returns:
            Formatted string with response and sources
        """
        output = []
        output.append("="*60)
        output.append(f"Query: {generated_response.query}")
        output.append("="*60)
        output.append(f"\n{generated_response.response}\n")
        output.append("-"*60)
        output.append("Sources:")
        output.append("-"*60)

        for citation in generated_response.citations:
            output.append(f"\n{citation['citation_id']} {citation['title']}")
            output.append(f"   Paper ID: {citation['arxiv_id']}")
            output.append(f"   Section: {citation['section_title']}")
            output.append(f"   Relevance Score: {citation['score']:.4f}")
            output.append(f"   Preview: {citation['text_preview']}")

        output.append("\n" + "="*60)

        return "\n".join(output)


def main():
    """Test the LLM generator."""
    # Create mock retrieved chunks
    mock_chunks = [
        {
            'text': 'The attention mechanism allows models to focus on different parts of the input sequence when producing each element of the output sequence. This is particularly useful in machine translation tasks.',
            'score': 0.92,
            'metadata': {
                'arxiv_id': '1706.03762',
                'title': 'Attention Is All You Need',
                'section_title': 'Introduction'
            }
        },
        {
            'text': 'Multi-head attention consists of several attention layers running in parallel. Each attention head learns different relationships in the data, allowing the model to attend to information from different representation subspaces.',
            'score': 0.87,
            'metadata': {
                'arxiv_id': '1706.03762',
                'title': 'Attention Is All You Need',
                'section_title': 'Model Architecture'
            }
        }
    ]

    # Initialize generator
    print("Initializing LLM generator...")
    generator = LLMGenerator()

    # Test query
    query = "What is the attention mechanism and how does multi-head attention work?"

    # Generate response
    print(f"\nGenerating response for: {query}")
    response = generator.generate_response(query, mock_chunks)

    # Display formatted output
    print(generator.format_response_with_sources(response))


if __name__ == "__main__":
    main()
